In [ ]:
#importing libs
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [ ]:
#loading the data
from google.colab import files
upload = files.upload()

Saving dataset.csv to dataset.csv


In [ ]:
#reading the csv
df = pd.read_csv('dataset.csv')
df.head()
df.shape

(5574, 2)

In [ ]:
#check for duplicates
df.drop_duplicates(inplace=True)
df.shape

(5171, 2)

In [ ]:
#checking for missing data
df.isnull().sum()
# df.shape

spam    0
sms     0
dtype: int64

In [ ]:
#stopwords management
nltk.download('stopwords')

def process(text):

    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)

    clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    
    return clean_words

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
#Showing application of process
# df['sms'].head().apply(process)
# df['sms'].head()

In [ ]:
#collection of text to a matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer

gVec = CountVectorizer(analyzer=process)
message_bow = gVec.fit_transform(df['sms'])
print(message_bow)

  (0, 2060)	1
  (0, 7555)	1
  (0, 8917)	1
  (0, 5769)	1
  (0, 1110)	1
  (0, 5218)	1
  (0, 8336)	1
  (0, 6937)	1
  (0, 11163)	1
  (0, 7668)	1
  (0, 6217)	1
  (0, 5217)	1
  (0, 1483)	1
  (0, 6906)	1
  (0, 4653)	1
  (0, 10965)	1
  (1, 3064)	1
  (1, 7701)	1
  (1, 2451)	1
  (1, 11072)	1
  (1, 10698)	1
  (1, 8590)	1
  (2, 1941)	1
  (2, 6331)	2
  (2, 423)	1
  :	:
  (5167, 6882)	1
  (5167, 11418)	1
  (5167, 6691)	1
  (5167, 6354)	1
  (5168, 8252)	1
  (5168, 3228)	1
  (5168, 3721)	1
  (5168, 10199)	1
  (5169, 7800)	1
  (5169, 11006)	1
  (5169, 8420)	1
  (5169, 10787)	1
  (5169, 6699)	1
  (5169, 9915)	1
  (5169, 6282)	1
  (5169, 6799)	1
  (5169, 5251)	1
  (5169, 7394)	1
  (5169, 6984)	1
  (5169, 7287)	1
  (5169, 4508)	1
  (5169, 5055)	1
  (5170, 8348)	1
  (5170, 10648)	1
  (5170, 3431)	1


In [ ]:
#80-20
#bow = bag of words
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(message_bow, df['spam'], test_size=0.20, random_state = 0)

In [ ]:
#shape of bow
print(message_bow.shape)
df.shape

(5171, 11425)


(5171, 2)

In [ ]:
#create and train Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(x_train, y_train)

In [ ]:
#print predicitons
print(classifier.predict(x_train))
# print(x_train.values)
print(y_train.values)
print(x_train.shape)
print(x_test.shape)

[1 0 0 ... 0 1 1]
[1 0 0 ... 0 1 1]
(4136, 11425)
(1035, 11425)


In [ ]:
#evaluation of the model
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(x_train)
print(classification_report(y_train, pred))
print()
print('Confusion Matrix')
print(confusion_matrix(y_train, pred))
print()
print('Accuracy: ',accuracy_score(y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3618
           1       0.99      0.98      0.98       518

    accuracy                           1.00      4136
   macro avg       0.99      0.99      0.99      4136
weighted avg       1.00      1.00      1.00      4136


Confusion Matrix
[[3611    7]
 [  12  506]]

Accuracy:  0.9954061895551257


In [ ]:
#predictions on test
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(x_test)
print(classification_report(y_test, pred))
print()
print('Confusion Matrix')
print(confusion_matrix(y_test, pred))
print()
print('Accuracy: ',accuracy_score(y_test, pred))



              precision    recall  f1-score   support

           0       0.99      0.96      0.97       900
           1       0.77      0.93      0.84       135

    accuracy                           0.95      1035
   macro avg       0.88      0.95      0.91      1035
weighted avg       0.96      0.95      0.96      1035


Confusion Matrix
[[862  38]
 [  9 126]]

Accuracy:  0.9545893719806763


In [ ]:
#reality
print((x_test.get_shape()))
msg1 = "Hello! How are you?"
msg2 = "IMPORTANT - You could be entitled up to £3,160 in compensation from mis-sold PPI on a credit card or loan. Please reply PPI for info or STOP to opt out."
msg3 = "how are you my friend?"
messages = [msg1,msg2,msg3]
# messages.append("hi friend")
#messages.append(msg2)

from sklearn.feature_extraction.text import CountVectorizer

msgs = pd.DataFrame(messages, columns=['sms'])
print(msgs['sms'])

bowch = gVec.transform(msgs['sms'])
print(bowch)
# myexample = CountVectorizer(analyzer=process).transform(msgs['sms'])
# print(myexample.shape)

print(classifier.predict(bowch))


(1035, 11425)
0                                  Hello! How are you?
1    IMPORTANT - You could be entitled up to £3,160...
2                               how are you my friend?
Name: sms, dtype: object
  (0, 2209)	1
  (1, 2312)	1
  (1, 3235)	1
  (1, 3549)	1
  (1, 5332)	1
  (1, 5623)	1
  (1, 5738)	1
  (1, 5774)	1
  (1, 6328)	1
  (1, 7354)	1
  (1, 7851)	1
  (1, 8617)	1
  (1, 9349)	1
  (2, 6717)	1
[0 1 0]


In [ ]:
#reality 2
from sklearn.externals import joblib
joblib.dump(classifier, "spamDetector.pkl")
joblib.dump(gVec, "gVec.pkl")

#rest is garbage
clf = joblib.load("spamDetector.pkl")
# print(clf.predict(x_test[0]))

# print(x_test[0].shape)
count = 0
# for i in x_test[0]:
#     if (i):
#         count+=1
# print(count)

#pca algo
#svd algo
#tfidf search
#cosine sim

from scipy.sparse import csr_matrix
test = csr_matrix((1, 11425), dtype=np.int8).toarray()
test[0][1] = 1
# print(test)
# print(test.shape)

# bowch.shape(bowch,shape=(3,5))

print(np.zeros((1,10000)).shape)
bowchnp = bowch.toarray()
np0 = np.zeros((1,11425-bowchnp.shape[1]))
print(bowchnp.shape, np0.shape)

final = np.concatenate((bowchnp, np0), axis=1)
print(final.shape)
finalcsr = csr_matrix(final)

# print('nig: ',bowch.shape)

# for i in bowch:
#     print(i)

print(classifier.predict(finalcsr))



(1, 10000)
(1, 11425) (1, 0)
(1, 11425)
[0]
